[workspace]
members = [
    "betree",
    "bectl"
]

[profile.dev.package."*"]
opt-level = 2
debug = false

[profile.test]
opt-level = 2

[profile.release.package."*"]
debug = false

[profile.release]
debug = true
opt-level = 3
lto = "fat"
codegen-units = 1
panic = "abort"
